import 'package:street_fighter/model/fighter.dart';

List<Fighter> fighters = [
  Fighter('Akuma', 'assets/akuma.gif', 'assets/icons/iconakuma.png', 'assets/icons/select_screen/akuma_ss.png',6),
  Fighter('Balrog', 'assets/balrog.gif', 'assets/icons/iconbalrog.png', 'assets/icons/select_screen/balrog_ss.png',5),
  Fighter('Bison', 'assets/bison.gif', 'assets/icons/iconbison.png', 'assets/icons/select_screen/bison_ss.png',4),
  Fighter('Choi', 'assets/choi.gif', 'assets/icons/iconchoi.png', 'assets/icons/select_screen/choi_ss.png',17),
  Fighter('Chun-li', 'assets/chunli.gif', 'assets/icons/iconchuli.png', 'assets/icons/select_screen/chuli_ss.png',11),
  Fighter('Dan', 'assets/dan.gif', 'assets/icons/icondan.png', 'assets/icons/select_screen/dan_ss.png',10),
  Fighter('Demitri', 'assets/demitri.gif', 'assets/icons/icondemitri.png', 'assets/icons/select_screen/demitri_ss.png',28),
  Fighter('Dhalsim', 'assets/dhalsim.gif', 'assets/icons/icondhalsim.png', 'assets/icons/select_screen/dhalsim_ss.png',22),
  Fighter('Geese', 'assets/geese.gif', 'assets/icons/icongeese.png', 'assets/icons/select_screen/geese_ss.png',1),
  Fighter('Genjuro', 'assets/genjuro.gif', 'assets/icons/icongenjuro.png', 'assets/icons/select_screen/genjuro_ss.png',2),
  Fighter('Goenitz', 'assets/goenitz.gif', 'assets/icons/icongoenitz.png', 'assets/icons/select_screen/goenitz_ss.png',3),
  Fighter('Guile', 'assets/guile.gif', 'assets/icons/iconguile.png', 'assets/icons/select_screen/guile_ss.png',12),
  Fighter('Honki', 'assets/honki.gif', 'assets/icons/iconmrkarate.png', 'assets/icons/select_screen/geese_ss.png',23),
  Fighter('Iori', 'assets/iori.gif', 'assets/icons/iconiori.png', 'assets/icons/select_screen/iori_ss.png',7),
  Fighter('Ken', 'assets/ken.gif', 'assets/icons/iconken.png', 'assets/icons/select_screen/ken_ss.png',15),
  Fighter('Kim', 'assets/kim.gif', 'assets/icons/iconkim.png', 'assets/icons/select_screen/kim_ss.png',18),
  Fighter('Kyo', 'assets/kyo.gif', 'assets/icons/iconkyo.png', 'assets/icons/select_screen/kyo_ss.png',8),
  Fighter('Mai', 'assets/mai.gif', 'assets/icons/iconmai.png', 'assets/icons/select_screen/mai_ss.png',9),
  Fighter('Ryo', 'assets/ryo.gif', 'assets/icons/iconryo.png', 'assets/icons/select_screen/ryo_ss.png',13),
  Fighter('Ryu', 'assets/ryu.gif', 'assets/icons/iconryu.png', 'assets/icons/select_screen/ryu_ss.png',20),
  Fighter('Sagat', 'assets/sagat.gif', 'assets/icons/iconsagat.png', 'assets/icons/select_screen/sagat_ss.png',16),
  Fighter('Shiki', 'assets/shiki.gif', 'assets/icons/iconshiki.png', 'assets/icons/select_screen/shiki_ss.png',19),
  Fighter('Shinakuma', 'assets/shinakuma.gif', 'assets/icons/iconshinakuma.png', 'assets/icons/select_screen/shinakuma_ss.png',27),
  Fighter('Terry', 'assets/terry.gif', 'assets/icons/iconterry.png', 'assets/icons/select_screen/terry_ss.png',14),
  Fighter('Tessa', 'assets/tessa.gif', 'assets/icons/icontessa.png', 'assets/icons/select_screen/tessa_ss.png',24),
  Fighter('Vega', 'assets/vega.gif', 'assets/icons/iconvega.png', 'assets/icons/select_screen/vega_ss.png',21),
  Fighter('ViolentKen', 'assets/violentken.gif', 'assets/icons/iconviolentken.png', 'assets/icons/select_screen/violentken_ss.png',26),
  Fighter('WildIori', 'assets/wildiori.gif', 'assets/icons/iconorochiiori.png', 'assets/icons/select_screen/orochiiori_ss.png',25)
];
