import 'package:street_fighter/fighter.dart';

List<Fighter> fighters = [
  Fighter('Akuma', 'assets/akuma.gif'),
  Fighter('Balrog', 'assets/balrog.gif'),
  Fighter('Bison', 'assets/bison.gif'),
  Fighter('Choi', 'assets/choi.gif'),
  Fighter('Chun-li', 'assets/chunli.gif'),
  Fighter('Dan', 'assets/dan.gif'),
  Fighter('Demitri', 'assets/demitri.gif'),
  Fighter('Dhalsim', 'assets/dhalsim.gif'),
  Fighter('Earthquake', 'assets/earthquake.gif'),
  Fighter('Geese', 'assets/geese.gif'),
  Fighter('Genjuro', 'assets/genjuro.gif'),
  Fighter('Goenitz', 'assets/goenitz.gif'),
  Fighter('Guile', 'assets/guile.gif'),
  Fighter('Honki', 'assets/honki.gif'),
  Fighter('Hugo', 'assets/hugo.gif'),
  Fighter('Iori', 'assets/iori.gif'),
  Fighter('Kasumi', 'assets/kasumi.gif'),
  Fighter('Ken', 'assets/ken.gif'),
  Fighter('Kim', 'assets/kim.gif'),
  Fighter('Kyo', 'assets/kyo.gif'),
  Fighter('Mai', 'assets/mai.gif'),
  Fighter('MrKarate', 'assets/mrkarate.gif'),
  Fighter('Ryo', 'assets/ryo.gif'),
  Fighter('Ryu', 'assets/ryu.gif'),
  Fighter('Sagat', 'assets/sagat.gif'),
  Fighter('Shiki', 'assets/shiki.gif'),
  Fighter('Shinakuma', 'assets/shinakuma.gif'),
  Fighter('Terry', 'assets/terry.gif'),
  Fighter('Tessa', 'assets/tessa.gif'),
  Fighter('Vega', 'assets/vega.gif'),
  Fighter('ViolentKen', 'assets/violentken.gif'),
  Fighter('WildIori', 'assets/wildiori.gif')
];
