import 'package:street_fighter/fighter.dart';

List<Fighter> fighters = [
  Fighter('Akuma', 'assets/akuma.gif', 'assets/icons/iconakuma.png'),
  Fighter('Balrog', 'assets/balrog.gif', 'assets/icons/iconbalrog.png'),
  Fighter('Bison', 'assets/bison.gif', 'assets/icons/iconbison.png'),
  Fighter('Choi', 'assets/choi.gif', 'assets/icons/iconchoi.png'),
  Fighter('Chun-li', 'assets/chunli.gif', 'assets/icons/iconchuli.png'),
  Fighter('Dan', 'assets/dan.gif', 'assets/icons/icondan.png'),
  Fighter('Demitri', 'assets/demitri.gif', 'assets/icons/icondemitri.png'),
  Fighter('Dhalsim', 'assets/dhalsim.gif', 'assets/icons/icondhalsim.png'),
  Fighter('Geese', 'assets/geese.gif', 'assets/icons/icongeese.png'),
  Fighter('Genjuro', 'assets/genjuro.gif', 'assets/icons/icongenjuro.png'),
  Fighter('Goenitz', 'assets/goenitz.gif', 'assets/icons/icongoenitz.png'),
  Fighter('Guile', 'assets/guile.gif', 'assets/icons/iconguile.png'),
  Fighter('Honki', 'assets/honki.gif', 'assets/icons/iconmrkarate.png'),
  Fighter('Iori', 'assets/iori.gif', 'assets/icons/iconiori.png'),
  Fighter('Kasumi', 'assets/kasumi.gif', 'assets/icons/iconkasumi.png'),
  Fighter('Ken', 'assets/ken.gif', 'assets/icons/iconken.png'),
  Fighter('Kim', 'assets/kim.gif', 'assets/icons/iconkim.png'),
  Fighter('Kyo', 'assets/kyo.gif', 'assets/icons/iconkyo.png'),
  Fighter('Mai', 'assets/mai.gif', 'assets/icons/iconmai.png'),
  Fighter('Ryo', 'assets/ryo.gif', 'assets/icons/iconryo.png'),
  Fighter('Ryu', 'assets/ryu.gif', 'assets/icons/iconryu.png'),
  Fighter('Sagat', 'assets/sagat.gif', 'assets/icons/iconsagat.png'),
  Fighter('Shiki', 'assets/shiki.gif', 'assets/icons/iconshiki.png'),
  Fighter('Shinakuma', 'assets/shinakuma.gif', 'assets/icons/iconshinakuma.png'),
  Fighter('Terry', 'assets/terry.gif', 'assets/icons/iconterry.png'),
  Fighter('Tessa', 'assets/tessa.gif', 'assets/icons/icontessa.png'),
  Fighter('Vega', 'assets/vega.gif', 'assets/icons/iconvega.png'),
  Fighter('ViolentKen', 'assets/violentken.gif', 'assets/icons/iconviolentken.png'),
  Fighter('WildIori', 'assets/wildiori.gif', 'assets/icons/iconorochiiori.png')
];
